support non-clean shutdown
OffchainLabs/go-ethereum pull request #155
Opened 2022-08-29 23:27 UTC by tsahee

Adds shutdown markers, and adds time on blockchain which invokes triedb cache writes

2022-08-29 23:35 UTC, joshuacolvin0 approved these changes
LGTM

2022-08-29 23:36 UTC, PlasmaPower commented on core/blockchain.go
> +	return bc.writeBlockAndSetHead(block, receipts, logs, state, emitHeadEvent)
Let's put this in blockchain_arbitrum.go to prevent merge conflicts

2022-08-30 16:53 UTC, PlasmaPower submitted a review, later dismissed
LGTM

2022-08-30 17:03 UTC, hkalodner requested changes

2022-08-30 17:03 UTC, hkalodner commented on core/blockchain_arbitrum.go
> +func (bc *BlockChain) FindRetentionBound() uint64 {
If `TrieRetention` is 0, the behavior should be the same as standard geth, right? Might be good to have an early exit to make that clear

2022-08-30 18:04 UTC, tsahee commented on core/blockchain_arbitrum.go
> +func (bc *BlockChain) FindRetentionBound() uint64 {
this would work better with a little-different search algo.. leaving it to later

2022-09-01 18:56 UTC, hkalodner approved these changes
LGTM

2022-09-01 20:53 UTC, merged