Merge v1.14.2
OffchainLabs/go-ethereum pull request #346
Opened 2024-07-25 11:46 UTC by amsanghi

2024-11-09 00:17 UTC, tsahee requested changes
small comments + need to solve a few conflicts when merging with origin/master. When possible with conflicts - use code from 14.2

2024-11-12 10:22 UTC, amsanghi commented on core/state/statedb.go
> +const TriesInMemory = 128
Done.

2024-11-12 10:22 UTC, amsanghi commented on core/state_transition.go
> +		st.state.AddBalance(st.evm.Context.Coinbase, fee, tracing.BalanceIncreaseRewardTransactionFee)
Done.

2024-11-19 02:39 UTC, tsahee requested changes
Minor comments.
Generally: I want to do a deeper review of how commit changed in 14.2 to think if we need more fixes but merge itself seems good.

2024-11-19 09:56 UTC, amsanghi commented on core/state/statedb.go
>  	if wasmCodeWriter.ValueSize() > 0 {
Done.

2024-11-22 00:15 UTC, tsahee approved these changes
LGTM

2024-11-22 00:15 UTC, merged