Add Clear method to SizeConstrainedCache
OffchainLabs/go-ethereum pull request #372
Opened 2024-11-07 05:59 UTC by ganeshvanahalli

Add useful methods such as `Clear` and `Remove` to `SizeConstrainedCache`. 
Corresponding nitro PR- https://github.com/OffchainLabs/nitro/pull/2754

Part of NIT-2837

2024-11-11 16:28 UTC, magicxyyz requested changes
we need to update cache size when removing items or purging the cache

2024-11-11 16:28 UTC, magicxyyz commented on common/lru/blob_lru.go
> +	c.lru.Purge()
we should set `c.size = 0` here

2024-11-12 06:16 UTC, ganeshvanahalli commented on common/lru/blob_lru.go
> +	c.lru.Remove(key)
Thanks! My bad, I overlooked while implementing these methods

2024-11-12 16:41 UTC, magicxyyz submitted a review, later dismissed
LGTM

2024-12-30 13:23 UTC, Tristan-Wilson approved these changes

2024-12-30 19:19 UTC, merged

2024-12-30 19:19 UTC, tsahee approved these changes
LGTM