add SyncMode option to PebbleExtraOptions
OffchainLabs/go-ethereum pull request #376
Opened 2024-11-19 17:00 UTC by magicxyyz

2024-11-21 16:03 UTC, diegoximenes approved these changes

2024-11-27 23:28 UTC, tsahee approved these changes
LGTM

2024-11-28 00:11 UTC, tsahee commented
Need to spend some time thinking what should be default for us

2024-12-10 21:28 UTC, tsahee requested changes

2024-12-10 21:28 UTC, tsahee commented on ethdb/pebble/pebble.go
> -		writeOptions: &pebble.WriteOptions{Sync: !ephemeral},
I think I'll feel better if our default will stay "on" and we could later think if the logic that goes for geth turning it off also fits us

2024-12-19 23:33 UTC, tsahee approved these changes
LGTM

2024-12-20 16:44 UTC, merged